"""empty message

Revision ID: 04d5e0e9f4b2
Revises: 
Create Date: 2021-08-04 19:38:05.466632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d5e0e9f4b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id_author', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_author', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_author')
    )
    op.create_table('publishers',
    sa.Column('id_publisher', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_publisher', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_publisher')
    )
    op.create_table('books',
    sa.Column('id_book', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_book', sa.String(length=255), nullable=False),
    sa.Column('year_published', sa.String(length=20), nullable=True),
    sa.Column('isbn', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('release_year', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('download', sa.String(), nullable=True),
    sa.Column('buy', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id_author'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id_publisher'], ),
    sa.PrimaryKeyConstraint('id_book')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('publishers')
    op.drop_table('authors')
    # ### end Alembic commands ###
