"""empty message

Revision ID: 0768fccd3973
Revises: 
Create Date: 2021-08-02 20:49:36.373491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0768fccd3973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('isbn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_book', sa.String(length=255), nullable=False),
    sa.Column('year_published', sa.String(length=20), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('release', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('download', sa.String(), nullable=False),
    sa.Column('buy', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('uptaded_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('controllers',
    sa.Column('id_controller', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_isbn', sa.Integer(), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['id_isbn'], ['books.isbn'], ),
    sa.PrimaryKeyConstraint('id_controller')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controllers')
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
